
stages:
- compile
- build
- test
- deploy  # dummy stage to follow the template guidelines
- review
- dast
- staging
- canary
- production
- incremental rollout 10%
- incremental rollout 25%
- incremental rollout 50%
- incremental rollout 100%
- performance
- cleanup




compile:
  image: node:latest
  stage: compile
  cache:
    paths:
    - node_modules/
  script:
  - export
  - npm install
  - npm run build
  artifacts:
    paths:
    - dist/spa

include:
- template: Auto-DevOps.gitlab-ci.yml

